[build]
builder = "nixpacks"

[deploy]
startCommand = "STREAMLIT_CONFIG=.streamlit/config.toml streamlit run bot.py --server.port=$PORT --server.address=0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 