[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 main.py"
